# Generated by Django 4.1.3 on 2022-11-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('ClaimsId', models.AutoField(primary_key=True, serialize=False)),
                ('ServiceDate', models.DateTimeField()),
                ('SubmittedProcedure', models.CharField(max_length=10)),
                ('Quadrant', models.CharField(max_length=2)),
                ('PlanGroupNumber', models.IntegerField(max_length=20)),
                ('SubscriberNumber', models.IntegerField(max_length=20)),
                ('ProviderNPI', models.IntegerField(max_length=20)),
                ('ProviderFees', models.IntegerField(max_length=20)),
                ('AllowedFees', models.IntegerField(max_length=20)),
                ('MemberCoinsurance', models.IntegerField(max_length=20)),
                ('MemberCopay', models.IntegerField(max_length=20)),
            ],
        ),
    ]
