# Generated by Django 4.1.3 on 2022-11-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='NetFee',
            field=models.IntegerField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
