# Generated by Django 4.1.3 on 2022-11-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claims_netfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='AllowedFees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='claims',
            name='MemberCoinsurance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='claims',
            name='MemberCopay',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='claims',
            name='NetFee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='claims',
            name='PlanGroupNumber',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='claims',
            name='ProviderFees',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='claims',
            name='ProviderNPI',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='claims',
            name='SubscriberNumber',
            field=models.IntegerField(),
        ),
    ]
