# Generated by Django 4.1.3 on 2022-11-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_alter_claims_allowedfees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='PlanGroupNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='claims',
            name='ProviderNPI',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='claims',
            name='SubscriberNumber',
            field=models.CharField(max_length=20),
        ),
    ]
