# Generated by Django 4.1.3 on 2022-11-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_alter_claims_plangroupnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='Quadrant',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
